# References:
# - http://about.travis-ci.org/docs/user/languages/python/
# - http://docs.travis-ci.com/user/docker/
sudo: required
language: python
services:
  - docker

#python:
#  - 2.4
#  - 2.6
#  - 2.7
before_install:
  - docker build -t ssato/rpmkit -f pkg/Dockerfile .
  - docker run ssato/rpmkit /bin/sh -c "test -d /root/rpmkit || git clone https://github.com/ssato/rpmkit.git /root/rpmkit; cd /root/rpmkit; bash -x ./pkg/runtest.sh"

env:
  global:
    - RUN_IN_DOCKER=yes
    - USER=root

script:
  - "./pkg/runtest.sh"

notifications:
  email:
    #on_success: always # default: change
    on_failure: always
